// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { LadybugDB } from './ladybug-db';

// insertion point for imports
import { LadybugSimulationDB } from './ladybugsimulation-db'

@Injectable({
  providedIn: 'root'
})
export class LadybugService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  LadybugServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private ladybugsUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.ladybugsUrl = origin + '/api/github.com/fullstack-lang/ladybugsim/go/v1/ladybugs';
  }

  /** GET ladybugs from the server */
  getLadybugs(): Observable<LadybugDB[]> {
    return this.http.get<LadybugDB[]>(this.ladybugsUrl)
      .pipe(
        tap(_ => this.log('fetched ladybugs')),
        catchError(this.handleError<LadybugDB[]>('getLadybugs', []))
      );
  }

  /** GET ladybug by id. Will 404 if id not found */
  getLadybug(id: number): Observable<LadybugDB> {
    const url = `${this.ladybugsUrl}/${id}`;
    return this.http.get<LadybugDB>(url).pipe(
      tap(_ => this.log(`fetched ladybug id=${id}`)),
      catchError(this.handleError<LadybugDB>(`getLadybug id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new ladybug to the server */
  postLadybug(ladybugdb: LadybugDB): Observable<LadybugDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    let _LadybugSimulation_Ladybugs_reverse = ladybugdb.LadybugSimulation_Ladybugs_reverse
    ladybugdb.LadybugSimulation_Ladybugs_reverse = new LadybugSimulationDB

    return this.http.post<LadybugDB>(this.ladybugsUrl, ladybugdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        ladybugdb.LadybugSimulation_Ladybugs_reverse = _LadybugSimulation_Ladybugs_reverse
        this.log(`posted ladybugdb id=${ladybugdb.ID}`)
      }),
      catchError(this.handleError<LadybugDB>('postLadybug'))
    );
  }

  /** DELETE: delete the ladybugdb from the server */
  deleteLadybug(ladybugdb: LadybugDB | number): Observable<LadybugDB> {
    const id = typeof ladybugdb === 'number' ? ladybugdb : ladybugdb.ID;
    const url = `${this.ladybugsUrl}/${id}`;

    return this.http.delete<LadybugDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted ladybugdb id=${id}`)),
      catchError(this.handleError<LadybugDB>('deleteLadybug'))
    );
  }

  /** PUT: update the ladybugdb on the server */
  updateLadybug(ladybugdb: LadybugDB): Observable<LadybugDB> {
    const id = typeof ladybugdb === 'number' ? ladybugdb : ladybugdb.ID;
    const url = `${this.ladybugsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    let _LadybugSimulation_Ladybugs_reverse = ladybugdb.LadybugSimulation_Ladybugs_reverse
    ladybugdb.LadybugSimulation_Ladybugs_reverse = new LadybugSimulationDB

    return this.http.put<LadybugDB>(url, ladybugdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        ladybugdb.LadybugSimulation_Ladybugs_reverse = _LadybugSimulation_Ladybugs_reverse
        this.log(`updated ladybugdb id=${ladybugdb.ID}`)
      }),
      catchError(this.handleError<LadybugDB>('updateLadybug'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
