// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { LadybugSimulationDB } from './ladybugsimulation-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class LadybugSimulationService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  LadybugSimulationServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private ladybugsimulationsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.ladybugsimulationsUrl = origin + '/api/github.com/fullstack-lang/ladybugsim/go/v1/ladybugsimulations';
  }

  /** GET ladybugsimulations from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string): Observable<LadybugSimulationDB[]> {
    return this.getLadybugSimulations(GONG__StackPath)
  }
  getLadybugSimulations(GONG__StackPath: string): Observable<LadybugSimulationDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<LadybugSimulationDB[]>(this.ladybugsimulationsUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched ladybugsimulations')),
        catchError(this.handleError<LadybugSimulationDB[]>('getLadybugSimulations', []))
      );
  }

  /** GET ladybugsimulation by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string): Observable<LadybugSimulationDB> {
	return this.getLadybugSimulation(id, GONG__StackPath)
  }
  getLadybugSimulation(id: number, GONG__StackPath: string): Observable<LadybugSimulationDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.ladybugsimulationsUrl}/${id}`;
    return this.http.get<LadybugSimulationDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched ladybugsimulation id=${id}`)),
      catchError(this.handleError<LadybugSimulationDB>(`getLadybugSimulation id=${id}`))
    );
  }

  /** POST: add a new ladybugsimulation to the server */
  post(ladybugsimulationdb: LadybugSimulationDB, GONG__StackPath: string): Observable<LadybugSimulationDB> {
    return this.postLadybugSimulation(ladybugsimulationdb, GONG__StackPath)	
  }
  postLadybugSimulation(ladybugsimulationdb: LadybugSimulationDB, GONG__StackPath: string): Observable<LadybugSimulationDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    let Ladybugs = ladybugsimulationdb.Ladybugs
    ladybugsimulationdb.Ladybugs = []

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<LadybugSimulationDB>(this.ladybugsimulationsUrl, ladybugsimulationdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
	      ladybugsimulationdb.Ladybugs = Ladybugs
        // this.log(`posted ladybugsimulationdb id=${ladybugsimulationdb.ID}`)
      }),
      catchError(this.handleError<LadybugSimulationDB>('postLadybugSimulation'))
    );
  }

  /** DELETE: delete the ladybugsimulationdb from the server */
  delete(ladybugsimulationdb: LadybugSimulationDB | number, GONG__StackPath: string): Observable<LadybugSimulationDB> {
    return this.deleteLadybugSimulation(ladybugsimulationdb, GONG__StackPath)
  }
  deleteLadybugSimulation(ladybugsimulationdb: LadybugSimulationDB | number, GONG__StackPath: string): Observable<LadybugSimulationDB> {
    const id = typeof ladybugsimulationdb === 'number' ? ladybugsimulationdb : ladybugsimulationdb.ID;
    const url = `${this.ladybugsimulationsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<LadybugSimulationDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted ladybugsimulationdb id=${id}`)),
      catchError(this.handleError<LadybugSimulationDB>('deleteLadybugSimulation'))
    );
  }

  /** PUT: update the ladybugsimulationdb on the server */
  update(ladybugsimulationdb: LadybugSimulationDB, GONG__StackPath: string): Observable<LadybugSimulationDB> {
    return this.updateLadybugSimulation(ladybugsimulationdb, GONG__StackPath)
  }
  updateLadybugSimulation(ladybugsimulationdb: LadybugSimulationDB, GONG__StackPath: string): Observable<LadybugSimulationDB> {
    const id = typeof ladybugsimulationdb === 'number' ? ladybugsimulationdb : ladybugsimulationdb.ID;
    const url = `${this.ladybugsimulationsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    let Ladybugs = ladybugsimulationdb.Ladybugs
    ladybugsimulationdb.Ladybugs = []

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<LadybugSimulationDB>(url, ladybugsimulationdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
	      ladybugsimulationdb.Ladybugs = Ladybugs
        // this.log(`updated ladybugsimulationdb id=${ladybugsimulationdb.ID}`)
      }),
      catchError(this.handleError<LadybugSimulationDB>('updateLadybugSimulation'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in LadybugSimulationService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("LadybugSimulationService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
