// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { UpdateSpeedEventDB } from './updatespeedevent-db';

@Injectable({
  providedIn: 'root'
})
export class UpdateSpeedEventService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  UpdateSpeedEventServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private updatespeedeventsUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
	let origin = this.document.location.origin
    
	// if debugging with ng, replace 4200 with 8080
	origin = origin.replace("4200", "8080")

    // compute path to the service
    this.updatespeedeventsUrl = origin + '/api/github.com/fullstack-lang/ladybugsim/go/v1/updatespeedevents';
   }

  /** GET updatespeedevents from the server */
  getUpdateSpeedEvents(): Observable<UpdateSpeedEventDB[]> {
    return this.http.get<UpdateSpeedEventDB[]>(this.updatespeedeventsUrl)
      .pipe(
        tap(_ => this.log('fetched updatespeedevents')),
        catchError(this.handleError<UpdateSpeedEventDB[]>('getUpdateSpeedEvents', []))
      );
  }

  /** GET updatespeedevent by id. Will 404 if id not found */
  getUpdateSpeedEvent(id: number): Observable<UpdateSpeedEventDB> {
    const url = `${this.updatespeedeventsUrl}/${id}`;
    return this.http.get<UpdateSpeedEventDB>(url).pipe(
      tap(_ => this.log(`fetched updatespeedevent id=${id}`)),
      catchError(this.handleError<UpdateSpeedEventDB>(`getUpdateSpeedEvent id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new updatespeedevent to the server */
  postUpdateSpeedEvent(updatespeedeventdb: UpdateSpeedEventDB): Observable<UpdateSpeedEventDB> {

		// insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

		return this.http.post<UpdateSpeedEventDB>(this.updatespeedeventsUrl, updatespeedeventdb, this.httpOptions).pipe(
			tap(_ => {
				// insertion point for restoration of reverse pointers
				this.log(`posted updatespeedeventdb id=${updatespeedeventdb.ID}`)
			}),
			catchError(this.handleError<UpdateSpeedEventDB>('postUpdateSpeedEvent'))
		);
  }

  /** DELETE: delete the updatespeedeventdb from the server */
  deleteUpdateSpeedEvent(updatespeedeventdb: UpdateSpeedEventDB | number): Observable<UpdateSpeedEventDB> {
    const id = typeof updatespeedeventdb === 'number' ? updatespeedeventdb : updatespeedeventdb.ID;
    const url = `${this.updatespeedeventsUrl}/${id}`;

    return this.http.delete<UpdateSpeedEventDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted updatespeedeventdb id=${id}`)),
      catchError(this.handleError<UpdateSpeedEventDB>('deleteUpdateSpeedEvent'))
    );
  }

  /** PUT: update the updatespeedeventdb on the server */
  updateUpdateSpeedEvent(updatespeedeventdb: UpdateSpeedEventDB): Observable<UpdateSpeedEventDB> {
    const id = typeof updatespeedeventdb === 'number' ? updatespeedeventdb : updatespeedeventdb.ID;
    const url = `${this.updatespeedeventsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.put(url, updatespeedeventdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated updatespeedeventdb id=${updatespeedeventdb.ID}`)
      }),
      catchError(this.handleError<UpdateSpeedEventDB>('updateUpdateSpeedEvent'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
