// generated by MultiCodeGeneratorNgService
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { UpdatePositionEventAPI } from './updatepositionevent-api';
import { UpdatePositionEventDB } from './updatepositionevent-db';

@Injectable({
  providedIn: 'root'
})
export class UpdatePositionEventService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  UpdatePositionEventServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private updatepositioneventsUrl = 'http://localhost:8080/api/github.com/fullstack-lang/ladybugsim/go/v1/updatepositionevents';

  constructor(
    private http: HttpClient
  ) { }

  /** GET updatepositionevents from the server */
  getUpdatePositionEvents(): Observable<UpdatePositionEventDB[]> {
    return this.http.get<UpdatePositionEventDB[]>(this.updatepositioneventsUrl)
      .pipe(
        tap(_ => this.log('fetched updatepositionevents')),
        catchError(this.handleError<UpdatePositionEventDB[]>('getUpdatePositionEvents', []))
      );
  }

  /** GET updatepositionevent by id. Will 404 if id not found */
  getUpdatePositionEvent(id: number): Observable<UpdatePositionEventDB> {
    const url = `${this.updatepositioneventsUrl}/${id}`;
    return this.http.get<UpdatePositionEventDB>(url).pipe(
      tap(_ => this.log(`fetched updatepositionevent id=${id}`)),
      catchError(this.handleError<UpdatePositionEventDB>(`getUpdatePositionEvent id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new updatepositionevent to the server */
  postUpdatePositionEvent(updatepositioneventdb: UpdatePositionEventDB): Observable<UpdatePositionEventDB> {

		// insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

		return this.http.post<UpdatePositionEventDB>(this.updatepositioneventsUrl, updatepositioneventdb, this.httpOptions).pipe(
			tap(_ => {
				// insertion point for restoration of reverse pointers
				this.log(`posted updatepositioneventdb id=${updatepositioneventdb.ID}`)
			}),
			catchError(this.handleError<UpdatePositionEventDB>('postUpdatePositionEvent'))
		);
  }

  /** DELETE: delete the updatepositioneventdb from the server */
  deleteUpdatePositionEvent(updatepositioneventdb: UpdatePositionEventDB | number): Observable<UpdatePositionEventDB> {
    const id = typeof updatepositioneventdb === 'number' ? updatepositioneventdb : updatepositioneventdb.ID;
    const url = `${this.updatepositioneventsUrl}/${id}`;

    return this.http.delete<UpdatePositionEventDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted updatepositioneventdb id=${id}`)),
      catchError(this.handleError<UpdatePositionEventDB>('deleteUpdatePositionEvent'))
    );
  }

  /** PUT: update the updatepositioneventdb on the server */
  updateUpdatePositionEvent(updatepositioneventdb: UpdatePositionEventDB): Observable<UpdatePositionEventDB> {
    const id = typeof updatepositioneventdb === 'number' ? updatepositioneventdb : updatepositioneventdb.ID;
    const url = `${this.updatepositioneventsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.put(url, updatepositioneventdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated updatepositioneventdb id=${updatepositioneventdb.ID}`)
      }),
      catchError(this.handleError<UpdatePositionEventDB>('updateUpdatePositionEvent'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
