// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { UpdateSpeedEventDB } from '../updatespeedevent-db'
import { UpdateSpeedEventService } from '../updatespeedevent.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-updatespeedeventstable',
  templateUrl: './updatespeedevents-table.component.html',
  styleUrls: ['./updatespeedevents-table.component.css'],
})
export class UpdateSpeedEventsTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of UpdateSpeedEvent instances
  selection: SelectionModel<UpdateSpeedEventDB> = new (SelectionModel)
  initialSelection = new Array<UpdateSpeedEventDB>()

  // the data source for the table
  updatespeedevents: UpdateSpeedEventDB[] = []
  matTableDataSource: MatTableDataSource<UpdateSpeedEventDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.updatespeedevents
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (updatespeedeventDB: UpdateSpeedEventDB, property: string) => {
      switch (property) {
        // insertion point for specific sorting accessor
        case 'Name':
          return updatespeedeventDB.Name;

        case 'Duration':
          return updatespeedeventDB.Duration;

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (updatespeedeventDB: UpdateSpeedEventDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the updatespeedeventDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += updatespeedeventDB.Name.toLowerCase()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private updatespeedeventService: UpdateSpeedEventService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of updatespeedevent instances
    public dialogRef: MatDialogRef<UpdateSpeedEventsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.updatespeedeventService.UpdateSpeedEventServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getUpdateSpeedEvents()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Duration",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Duration",
      ]
      this.selection = new SelectionModel<UpdateSpeedEventDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getUpdateSpeedEvents()
    this.matTableDataSource = new MatTableDataSource(this.updatespeedevents)
  }

  getUpdateSpeedEvents(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.updatespeedevents = this.frontRepo.UpdateSpeedEvents_array;

        // insertion point for variables Recoveries
        // compute strings for durations
        for (let updatespeedevent of this.updatespeedevents) {
          updatespeedevent.Duration_string =
            Math.floor(updatespeedevent.Duration / (3600 * 1000 * 1000 * 1000)) + "H " +
            Math.floor(updatespeedevent.Duration % (3600 * 1000 * 1000 * 1000) / (60 * 1000 * 1000 * 1000)) + "M " +
            updatespeedevent.Duration % (60 * 1000 * 1000 * 1000) / (1000 * 1000 * 1000) + "S"
        }

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          this.updatespeedevents.forEach(
            updatespeedevent => {
              let ID = this.dialogData.ID
              let revPointer = updatespeedevent[this.dialogData.ReversePointer as keyof UpdateSpeedEventDB] as unknown as NullInt64
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(updatespeedevent)
              }
            }
          )
          this.selection = new SelectionModel<UpdateSpeedEventDB>(allowMultiSelect, this.initialSelection);
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, UpdateSpeedEventDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as UpdateSpeedEventDB[]
          for (let associationInstance of sourceField) {
            let updatespeedevent = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as UpdateSpeedEventDB
            this.initialSelection.push(updatespeedevent)
          }

          this.selection = new SelectionModel<UpdateSpeedEventDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.updatespeedevents
      }
    )
  }

  // newUpdateSpeedEvent initiate a new updatespeedevent
  // create a new UpdateSpeedEvent objet
  newUpdateSpeedEvent() {
  }

  deleteUpdateSpeedEvent(updatespeedeventID: number, updatespeedevent: UpdateSpeedEventDB) {
    // list of updatespeedevents is truncated of updatespeedevent before the delete
    this.updatespeedevents = this.updatespeedevents.filter(h => h !== updatespeedevent);

    this.updatespeedeventService.deleteUpdateSpeedEvent(updatespeedeventID).subscribe(
      updatespeedevent => {
        this.updatespeedeventService.UpdateSpeedEventServiceChanged.next("delete")
      }
    );
  }

  editUpdateSpeedEvent(updatespeedeventID: number, updatespeedevent: UpdateSpeedEventDB) {

  }

  // display updatespeedevent in router
  displayUpdateSpeedEventInRouter(updatespeedeventID: number) {
    this.router.navigate(["github_com_fullstack_lang_ladybugsim_go-" + "updatespeedevent-display", updatespeedeventID])
  }

  // set editor outlet
  setEditorRouterOutlet(updatespeedeventID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_ladybugsim_go_editor: ["github_com_fullstack_lang_ladybugsim_go-" + "updatespeedevent-detail", updatespeedeventID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(updatespeedeventID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_ladybugsim_go_presentation: ["github_com_fullstack_lang_ladybugsim_go-" + "updatespeedevent-presentation", updatespeedeventID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.updatespeedevents.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.updatespeedevents.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<UpdateSpeedEventDB>()

      // reset all initial selection of updatespeedevent that belong to updatespeedevent
      this.initialSelection.forEach(
        updatespeedevent => {
          let index = updatespeedevent[this.dialogData.ReversePointer as keyof UpdateSpeedEventDB] as unknown as NullInt64
          index.Int64 = 0
          index.Valid = true
          toUpdate.add(updatespeedevent)
        }
      )

      // from selection, set updatespeedevent that belong to updatespeedevent
      this.selection.selected.forEach(
        updatespeedevent => {
          let ID = this.dialogData.ID as number
          let reversePointer = updatespeedevent[this.dialogData.ReversePointer  as keyof UpdateSpeedEventDB] as unknown as NullInt64
          reversePointer.Int64 = ID
          toUpdate.add(updatespeedevent)
        }
      )

      // update all updatespeedevent (only update selection & initial selection)
      toUpdate.forEach(
        updatespeedevent => {
          this.updatespeedeventService.updateUpdateSpeedEvent(updatespeedevent)
            .subscribe(updatespeedevent => {
              this.updatespeedeventService.UpdateSpeedEventServiceChanged.next("update")
            });
        }
      )
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, UpdateSpeedEventDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedUpdateSpeedEvent = new Set<number>()
      for (let updatespeedevent of this.initialSelection) {
        if (this.selection.selected.includes(updatespeedevent)) {
          // console.log("updatespeedevent " + updatespeedevent.Name + " is still selected")
        } else {
          console.log("updatespeedevent " + updatespeedevent.Name + " has been unselected")
          unselectedUpdateSpeedEvent.add(updatespeedevent.ID)
          console.log("is unselected " + unselectedUpdateSpeedEvent.has(updatespeedevent.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let updatespeedevent = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as UpdateSpeedEventDB
      if (unselectedUpdateSpeedEvent.has(updatespeedevent.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<UpdateSpeedEventDB>) = new Array<UpdateSpeedEventDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          updatespeedevent => {
            if (!this.initialSelection.includes(updatespeedevent)) {
              // console.log("updatespeedevent " + updatespeedevent.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + updatespeedevent.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField+"ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = updatespeedevent.ID

              let indexDB = associationInstance[this.dialogData.IntermediateStructField+"DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = updatespeedevent.ID

              this.frontRepoService.postService( this.dialogData.IntermediateStruct, associationInstance )

            } else {
              // console.log("updatespeedevent " + updatespeedevent.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<UpdateSpeedEventDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
