// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { UpdatePositionEventDB } from '../updatepositionevent-db'
import { UpdatePositionEventService } from '../updatepositionevent.service'

import { FrontRepoService, FrontRepo, NullInt64 } from '../front-repo.service'
@Component({
  selector: 'lib-updatepositionevent-sorting',
  templateUrl: './updatepositionevent-sorting.component.html',
  styleUrls: ['./updatepositionevent-sorting.component.css']
})
export class UpdatePositionEventSortingComponent implements OnInit {

  frontRepo: FrontRepo

  // array of UpdatePositionEvent instances that are in the association
  associatedUpdatePositionEvents = new Array<UpdatePositionEventDB>();

  constructor(
    private updatepositioneventService: UpdatePositionEventService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of updatepositionevent instances
    public dialogRef: MatDialogRef<UpdatePositionEventSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getUpdatePositionEvents()
  }

  getUpdatePositionEvents(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let updatepositionevent of this.frontRepo.UpdatePositionEvents_array) {
          let ID = this.dialogData.ID
          let revPointerID = updatepositionevent[this.dialogData.ReversePointer]
          let revPointerID_Index = updatepositionevent[this.dialogData.ReversePointer+"_Index"]
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedUpdatePositionEvents.push(updatepositionevent)
          }
        }

        // sort associated updatepositionevent according to order
        this.associatedUpdatePositionEvents.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer+"_Index"]
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer+"_Index"]
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }  
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedUpdatePositionEvents, event.previousIndex, event.currentIndex);

    // set the order of UpdatePositionEvent instances
    let index = 0
    
    for (let updatepositionevent of this.associatedUpdatePositionEvents) {
      let revPointerID_Index = updatepositionevent[this.dialogData.ReversePointer+"_Index"]
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedUpdatePositionEvents.forEach(
      updatepositionevent => {
        this.updatepositioneventService.updateUpdatePositionEvent(updatepositionevent)
          .subscribe(updatepositionevent => {
            this.updatepositioneventService.UpdatePositionEventServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of '+ this.dialogData.ReversePointer+' done');
  }
}
