// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, NullInt64, SelectionMode } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { LadybugDB } from '../ladybug-db'
import { LadybugService } from '../ladybug.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-ladybugstable',
  templateUrl: './ladybugs-table.component.html',
  styleUrls: ['./ladybugs-table.component.css'],
})
export class LadybugsTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode

  // used if the component is called as a selection component of Ladybug instances
  selection: SelectionModel<LadybugDB>;
  initialSelection = new Array<LadybugDB>();

  // the data source for the table
  ladybugs: LadybugDB[];
  matTableDataSource: MatTableDataSource<LadybugDB>

  // front repo, that will be referenced by this.ladybugs
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (ladybugDB: LadybugDB, property: string) => {
      switch (property) {
        // insertion point for specific sorting accessor
        case 'TechName':
          return ladybugDB.TechName;

        case 'Name':
          return ladybugDB.Name;

        case 'Id':
          return ladybugDB.Id;

        case 'Position':
          return ladybugDB.Position;

        case 'Speed':
          return ladybugDB.Speed;

        case 'Ladybugs':
          return this.frontRepo.LadybugSimulations.get(ladybugDB.LadybugSimulation_LadybugsDBID.Int64)?.Name;

        default:
          return LadybugDB[property];
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (ladybugDB: LadybugDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the ladybugDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += ladybugDB.TechName.toLowerCase()
      mergedContent += ladybugDB.Name.toLowerCase()
      mergedContent += ladybugDB.Id.toString()
      mergedContent += ladybugDB.Position.toString()
      mergedContent += ladybugDB.Speed.toString()
      if (ladybugDB.LadybugSimulation_LadybugsDBID.Int64 != 0) {
        mergedContent += this.frontRepo.LadybugSimulations.get(ladybugDB.LadybugSimulation_LadybugsDBID.Int64)?.Name.toLowerCase()
      }


      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private ladybugService: LadybugService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of ladybug instances
    public dialogRef: MatDialogRef<LadybugsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.ladybugService.LadybugServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getLadybugs()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "TechName",
        "Name",
        "Id",
        "Position",
        "Speed",
        "Ladybugs",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "TechName",
        "Name",
        "Id",
        "Position",
        "Speed",
        "Ladybugs",
      ]
      this.selection = new SelectionModel<LadybugDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getLadybugs()
    this.matTableDataSource = new MatTableDataSource(this.ladybugs)
  }

  getLadybugs(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.ladybugs = this.frontRepo.Ladybugs_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          this.ladybugs.forEach(
            ladybug => {
              let ID = this.dialogData.ID
              let revPointer = ladybug[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(ladybug)
              }
            }
          )
          this.selection = new SelectionModel<LadybugDB>(allowMultiSelect, this.initialSelection);
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

          if (sourceInstance[this.dialogData.SourceField]) {
            for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
              let ladybug = associationInstance[this.dialogData.IntermediateStructField]
              this.initialSelection.push(ladybug)
            }
          }
          this.selection = new SelectionModel<LadybugDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.ladybugs
      }
    )
  }

  // newLadybug initiate a new ladybug
  // create a new Ladybug objet
  newLadybug() {
  }

  deleteLadybug(ladybugID: number, ladybug: LadybugDB) {
    // list of ladybugs is truncated of ladybug before the delete
    this.ladybugs = this.ladybugs.filter(h => h !== ladybug);

    this.ladybugService.deleteLadybug(ladybugID).subscribe(
      ladybug => {
        this.ladybugService.LadybugServiceChanged.next("delete")
      }
    );
  }

  editLadybug(ladybugID: number, ladybug: LadybugDB) {

  }

  // display ladybug in router
  displayLadybugInRouter(ladybugID: number) {
    this.router.navigate(["github_com_fullstack_lang_ladybugsim_go-" + "ladybug-display", ladybugID])
  }

  // set editor outlet
  setEditorRouterOutlet(ladybugID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_ladybugsim_go_editor: ["github_com_fullstack_lang_ladybugsim_go-" + "ladybug-detail", ladybugID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(ladybugID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_ladybugsim_go_presentation: ["github_com_fullstack_lang_ladybugsim_go-" + "ladybug-presentation", ladybugID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.ladybugs.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.ladybugs.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<LadybugDB>()

      // reset all initial selection of ladybug that belong to ladybug
      this.initialSelection.forEach(
        ladybug => {
          ladybug[this.dialogData.ReversePointer].Int64 = 0
          ladybug[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(ladybug)
        }
      )

      // from selection, set ladybug that belong to ladybug
      this.selection.selected.forEach(
        ladybug => {
          let ID = +this.dialogData.ID
          ladybug[this.dialogData.ReversePointer].Int64 = ID
          ladybug[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(ladybug)
        }
      )

      // update all ladybug (only update selection & initial selection)
      toUpdate.forEach(
        ladybug => {
          this.ladybugService.updateLadybug(ladybug)
            .subscribe(ladybug => {
              this.ladybugService.LadybugServiceChanged.next("update")
            });
        }
      )
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedLadybug = new Set<number>()
      for (let ladybug of this.initialSelection) {
        if (this.selection.selected.includes(ladybug)) {
          // console.log("ladybug " + ladybug.Name + " is still selected")
        } else {
          console.log("ladybug " + ladybug.Name + " has been unselected")
          unselectedLadybug.add(ladybug.ID)
          console.log("is unselected " + unselectedLadybug.has(ladybug.ID))
        }
      }

      // delete the association instance
      if (sourceInstance[this.dialogData.SourceField]) {
        for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
          let ladybug = associationInstance[this.dialogData.IntermediateStructField]
          if (unselectedLadybug.has(ladybug.ID)) {

            this.frontRepoService.deleteService( this.dialogData.IntermediateStruct, associationInstance )
          }
        }
      }

      // is the source array is emptyn create it
      if (sourceInstance[this.dialogData.SourceField] == undefined) {
        sourceInstance[this.dialogData.SourceField] = new Array<any>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField]) {
        this.selection.selected.forEach(
          ladybug => {
            if (!this.initialSelection.includes(ladybug)) {
              // console.log("ladybug " + ladybug.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + ladybug.Name,
              }

              associationInstance[this.dialogData.IntermediateStructField+"ID"] = new NullInt64
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Int64 = ladybug.ID
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Valid = true

              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"] = new NullInt64
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Int64 = sourceInstance["ID"]
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Valid = true

              this.frontRepoService.postService( this.dialogData.IntermediateStruct, associationInstance )

            } else {
              // console.log("ladybug " + ladybug.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<LadybugDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
