// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { LadybugDB } from '../ladybug-db'
import { LadybugService } from '../ladybug.service'

// insertion point for additional imports

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-ladybugstable',
  templateUrl: './ladybugs-table.component.html',
  styleUrls: ['./ladybugs-table.component.css'],
})
export class LadybugsTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of Ladybug instances
  selection: SelectionModel<LadybugDB> = new (SelectionModel)
  initialSelection = new Array<LadybugDB>()

  // the data source for the table
  ladybugs: LadybugDB[] = []
  matTableDataSource: MatTableDataSource<LadybugDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.ladybugs
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (ladybugDB: LadybugDB, property: string) => {
      switch (property) {
        case 'ID':
          return ladybugDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return ladybugDB.Name;

        case 'Id':
          return ladybugDB.Id;

        case 'Position':
          return ladybugDB.Position;

        case 'Speed':
          return ladybugDB.Speed;

        case 'LadybugStatus':
          return ladybugDB.LadybugStatus;

        case 'LadybugSimulation_Ladybugs':
          if (this.frontRepo.LadybugSimulations.get(ladybugDB.LadybugSimulation_LadybugsDBID.Int64) != undefined) {
            return this.frontRepo.LadybugSimulations.get(ladybugDB.LadybugSimulation_LadybugsDBID.Int64)!.Name
          } else {
            return ""
          }

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (ladybugDB: LadybugDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the ladybugDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += ladybugDB.Name.toLowerCase()
      mergedContent += ladybugDB.Id.toString()
      mergedContent += ladybugDB.Position.toString()
      mergedContent += ladybugDB.Speed.toString()
      mergedContent += ladybugDB.LadybugStatus.toLowerCase()
      if (ladybugDB.LadybugSimulation_LadybugsDBID.Int64 != 0) {
        mergedContent += this.frontRepo.LadybugSimulations.get(ladybugDB.LadybugSimulation_LadybugsDBID.Int64)!.Name.toLowerCase()
      }


      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private ladybugService: LadybugService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of ladybug instances
    public dialogRef: MatDialogRef<LadybugsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.ladybugService.LadybugServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getLadybugs()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Id",
        "Position",
        "Speed",
        "LadybugStatus",
        "LadybugSimulation_Ladybugs",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Id",
        "Position",
        "Speed",
        "LadybugStatus",
        "LadybugSimulation_Ladybugs",
      ]
      this.selection = new SelectionModel<LadybugDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getLadybugs()
    this.matTableDataSource = new MatTableDataSource(this.ladybugs)
  }

  getLadybugs(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.ladybugs = this.frontRepo.Ladybugs_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries
        
        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let ladybug of this.ladybugs) {
            let ID = this.dialogData.ID
            let revPointer = ladybug[this.dialogData.ReversePointer as keyof LadybugDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(ladybug)
            }
            this.selection = new SelectionModel<LadybugDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, LadybugDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as LadybugDB[]
          for (let associationInstance of sourceField) {
            let ladybug = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as LadybugDB
            this.initialSelection.push(ladybug)
          }

          this.selection = new SelectionModel<LadybugDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.ladybugs
      }
    )
  }

  // newLadybug initiate a new ladybug
  // create a new Ladybug objet
  newLadybug() {
  }

  deleteLadybug(ladybugID: number, ladybug: LadybugDB) {
    // list of ladybugs is truncated of ladybug before the delete
    this.ladybugs = this.ladybugs.filter(h => h !== ladybug);

    this.ladybugService.deleteLadybug(ladybugID).subscribe(
      ladybug => {
        this.ladybugService.LadybugServiceChanged.next("delete")
      }
    );
  }

  editLadybug(ladybugID: number, ladybug: LadybugDB) {

  }

  // display ladybug in router
  displayLadybugInRouter(ladybugID: number) {
    this.router.navigate(["github_com_fullstack_lang_ladybugsim_go-" + "ladybug-display", ladybugID])
  }

  // set editor outlet
  setEditorRouterOutlet(ladybugID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_ladybugsim_go_editor: ["github_com_fullstack_lang_ladybugsim_go-" + "ladybug-detail", ladybugID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(ladybugID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_ladybugsim_go_presentation: ["github_com_fullstack_lang_ladybugsim_go-" + "ladybug-presentation", ladybugID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.ladybugs.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.ladybugs.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<LadybugDB>()

      // reset all initial selection of ladybug that belong to ladybug
      for (let ladybug of this.initialSelection) {
        let index = ladybug[this.dialogData.ReversePointer as keyof LadybugDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(ladybug)

      }

      // from selection, set ladybug that belong to ladybug
      for (let ladybug of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = ladybug[this.dialogData.ReversePointer as keyof LadybugDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(ladybug)
      }


      // update all ladybug (only update selection & initial selection)
      for (let ladybug of toUpdate) {
        this.ladybugService.updateLadybug(ladybug)
          .subscribe(ladybug => {
            this.ladybugService.LadybugServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, LadybugDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedLadybug = new Set<number>()
      for (let ladybug of this.initialSelection) {
        if (this.selection.selected.includes(ladybug)) {
          // console.log("ladybug " + ladybug.Name + " is still selected")
        } else {
          console.log("ladybug " + ladybug.Name + " has been unselected")
          unselectedLadybug.add(ladybug.ID)
          console.log("is unselected " + unselectedLadybug.has(ladybug.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let ladybug = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as LadybugDB
      if (unselectedLadybug.has(ladybug.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<LadybugDB>) = new Array<LadybugDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          ladybug => {
            if (!this.initialSelection.includes(ladybug)) {
              // console.log("ladybug " + ladybug.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + ladybug.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = ladybug.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = ladybug.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("ladybug " + ladybug.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<LadybugDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
