// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { LadybugSimulationDB } from '../ladybugsimulation-db'
import { LadybugSimulationService } from '../ladybugsimulation.service'

import { FrontRepoService, FrontRepo, NullInt64 } from '../front-repo.service'
@Component({
  selector: 'lib-ladybugsimulation-sorting',
  templateUrl: './ladybugsimulation-sorting.component.html',
  styleUrls: ['./ladybugsimulation-sorting.component.css']
})
export class LadybugSimulationSortingComponent implements OnInit {

  frontRepo: FrontRepo

  // array of LadybugSimulation instances that are in the association
  associatedLadybugSimulations = new Array<LadybugSimulationDB>();

  constructor(
    private ladybugsimulationService: LadybugSimulationService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of ladybugsimulation instances
    public dialogRef: MatDialogRef<LadybugSimulationSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getLadybugSimulations()
  }

  getLadybugSimulations(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let ladybugsimulation of this.frontRepo.LadybugSimulations_array) {
          let ID = this.dialogData.ID
          let revPointerID = ladybugsimulation[this.dialogData.ReversePointer]
          let revPointerID_Index = ladybugsimulation[this.dialogData.ReversePointer+"_Index"]
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedLadybugSimulations.push(ladybugsimulation)
          }
        }

        // sort associated ladybugsimulation according to order
        this.associatedLadybugSimulations.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer+"_Index"]
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer+"_Index"]
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }  
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedLadybugSimulations, event.previousIndex, event.currentIndex);

    // set the order of LadybugSimulation instances
    let index = 0
    
    for (let ladybugsimulation of this.associatedLadybugSimulations) {
      let revPointerID_Index = ladybugsimulation[this.dialogData.ReversePointer+"_Index"]
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedLadybugSimulations.forEach(
      ladybugsimulation => {
        this.ladybugsimulationService.updateLadybugSimulation(ladybugsimulation)
          .subscribe(ladybugsimulation => {
            this.ladybugsimulationService.LadybugSimulationServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of '+ this.dialogData.ReversePointer+' done');
  }
}
