// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { UpdateSpeedEventDB } from '../updatespeedevent-db'
import { UpdateSpeedEventService } from '../updatespeedevent.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-updatespeedevent-sorting',
  templateUrl: './updatespeedevent-sorting.component.html',
  styleUrls: ['./updatespeedevent-sorting.component.css']
})
export class UpdateSpeedEventSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of UpdateSpeedEvent instances that are in the association
  associatedUpdateSpeedEvents = new Array<UpdateSpeedEventDB>();

  constructor(
    private updatespeedeventService: UpdateSpeedEventService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of updatespeedevent instances
    public dialogRef: MatDialogRef<UpdateSpeedEventSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getUpdateSpeedEvents()
  }

  getUpdateSpeedEvents(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let updatespeedevent of this.frontRepo.UpdateSpeedEvents_array) {
          let ID = this.dialogData.ID
          let revPointerID = updatespeedevent[this.dialogData.ReversePointer as keyof UpdateSpeedEventDB] as unknown as NullInt64
          let revPointerID_Index = updatespeedevent[this.dialogData.ReversePointer + "_Index" as keyof UpdateSpeedEventDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedUpdateSpeedEvents.push(updatespeedevent)
          }
        }

        // sort associated updatespeedevent according to order
        this.associatedUpdateSpeedEvents.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedUpdateSpeedEvents, event.previousIndex, event.currentIndex);

    // set the order of UpdateSpeedEvent instances
    let index = 0

    for (let updatespeedevent of this.associatedUpdateSpeedEvents) {
      let revPointerID_Index = updatespeedevent[this.dialogData.ReversePointer + "_Index" as keyof UpdateSpeedEventDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedUpdateSpeedEvents.forEach(
      updatespeedevent => {
        this.updatespeedeventService.updateUpdateSpeedEvent(updatespeedevent)
          .subscribe(updatespeedevent => {
            this.updatespeedeventService.UpdateSpeedEventServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer +' done');
  }
}
